#Database configuration for the Arffornia web shop integration
[database]
	host = "postgres-cluster.postgres.svc.cluster.local"
	port = 5432
	database = "arffornia"
	username = "${CFG_DB_USERNAME}"
	password = "${CFG_DB_PASSWORD}"

#Configuration for the Arffornia API connection
[api]
	#The base URL for the Arffornia API.
	baseUrl = "https://arffornia.com/api"
	#The service account Client ID for API authentication.
	clientId = "${CFG_SVC_ID}"
	#The service account Client Secret for API authentication. This should be kept private.
	clientSecret = "${CFG_SVC_PASSWORD}"
	#If true, the mod will attempt to migrate vanilla recipes for existing items on the next server startup. This should be manually set to false after a successful run.
	migrateOnStartup = true
